language: node_js
node_js:
  - "6.12.0"
  - "8"
  - "stable"
install:
  - npm install
script:
  - npm run build
  - npm run test-cov
after_success:
  - ./node_modules/.bin/nyc report -r text-lcov | ./node_modules/.bin/coveralls
